# Generated by Django 5.0.4 on 2024-05-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(default='default-book-cover.jpg', upload_to='books/%y/%m/%d')),
                ('author_name', models.CharField(max_length=50)),
                ('about_author', models.TextField()),
            ],
        ),
    ]
