# Generated by Django 5.0.4 on 2024-05-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(default='trending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
