# Generated by Django 5.0.4 on 2024-05-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_type_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default='no category', max_length=50, null=True),
        ),
    ]
