# Generated by Django 5.0.4 on 2024-05-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.IntegerField(default=[('trending', 'trending'), ('latest', 'latest')], max_length=50, null=True),
        ),
    ]
