# Generated by Django 5.0.4 on 2024-05-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('trending', 'trending'), ('latest', 'latest')], default='latest', max_length=50, null=True),
        ),
    ]
