# Generated by Django 5.0.4 on 2024-05-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isActive',
        ),
    ]
