# Generated by Django 5.0.4 on 2024-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_book_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='book',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
