# Generated by Django 5.0.4 on 2024-05-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_book_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.AddField(
            model_name='book',
            name='is_trending',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
