# Generated by Django 5.0.4 on 2024-05-13 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_book_book_type_book_is_trending'),
        ('profileModel', '0005_alter_profilemodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileModel.profilemodel'),
        ),
    ]
