# Generated by Django 5.0.4 on 2024-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
