# Generated by Django 5.0.4 on 2024-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_trending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='trending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
