# Generated by Django 5.0.4 on 2024-05-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
